### ISSUE TITLE
Make DATA_DIR configurable

### ISSUE THREAD

**Issue by sikmir** [LBeaudoux/tatoebatools#3]
While trying to use tatoebatools installed into read-only location, tatoebatools can't create DATA_DIR folder:
https://github.com/LBeaudoux/tatoebatools/blob/c2c223a60a32cc79c4b4f741b8b21db75c04b3c9/tatoebatools/config.py#L5
It would be great to make it configurable.

**Comment by LBeaudoux** [comment]
If I understand correctly, you would like to be able to change the path of the data directory associated with an instance of the `tatoeba` object. Moreover, modifying the data directory path potentially saved in a `tatoebatools` configuration file is not possible in your case since you are constrained by read-only.

In practice, you would like each import of `tatoeba` to look something like this:
```python
from tatoebatools import tatoeba
tatoeba.data_dir = "my/custom/writable/data/dir/"
```

**Comment by sikmir** [comment]
Yes, exactly. As a result I would like to set `data_dir` to `$XDG_DATA_HOME/tatoebatools` (that is `~/.local/share/tatoebatools` on Linux, see [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)).

**Comment by sikmir** [comment]
Here is my nix package for tatoebatools - https://github.com/sikmir/nur-packages/blob/master/pkgs/tools/dict/tatoebatools/default.nix, nix installs all packages into read-only nix store.

**Comment by LBeaudoux** [comment]
It is now possible to chose a custom data directory with the `dir-cfg` branch of the repo:
```python
from tatoebatools import tatoeba
tatoeba.dir = "my/custom/writable/data/dir/"
```
From now on, `tatoebatools` will also cache a few html files into the default temp directory.  @sikmir, if writing files in `/temp` is not an issue for you, I can merge this pull request and publish an update on PyPI.

**Comment by sikmir** [comment]
@LBeaudoux Thanks! It works now, temp dir is OK. Here is my simple example:
```python
import click
from xdg import XDG_DATA_HOME
from tatoebatools import ParallelCorpus, tatoeba

tatoeba.dir = XDG_DATA_HOME / "tatoebatools"

@click.group()
def cli():
    pass

@cli.command(short_help="Parallel corpus")
@click.argument('source_language')
@click.argument('target_language')
@click.option('--update', type=click.BOOL, default=False)
def parallel_corpus(source_language, target_language, update):
    for sentence, translation in ParallelCorpus(source_language, target_language, update):
        print("%s\t%s" % (sentence.text, translation.text));
```
Run with:
```bash
$ tatoeba parallel-corpus eng rus
```
P.S.: Thanks for such great tool! I really missed it while actively using Tatoeba corpus.

**Comment by LBeaudoux** [comment]
Thanks for sharing this example, it reminds me that _tatoebatools_ still lacks a CLI.
